// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import time "time"

// MetricCollector is an autogenerated mock type for the MetricCollector type
type MetricCollector struct {
	mock.Mock
}

// IncrementAttempts provides a mock function with given fields:
func (_m *MetricCollector) IncrementAttempts() {
	_m.Called()
}

// IncrementErrors provides a mock function with given fields:
func (_m *MetricCollector) IncrementErrors() {
	_m.Called()
}

// IncrementFailures provides a mock function with given fields:
func (_m *MetricCollector) IncrementFailures() {
	_m.Called()
}

// IncrementFallbackFailures provides a mock function with given fields:
func (_m *MetricCollector) IncrementFallbackFailures() {
	_m.Called()
}

// IncrementFallbackSuccesses provides a mock function with given fields:
func (_m *MetricCollector) IncrementFallbackSuccesses() {
	_m.Called()
}

// IncrementQueueSize provides a mock function with given fields:
func (_m *MetricCollector) IncrementQueueSize() {
	_m.Called()
}

// IncrementRejects provides a mock function with given fields:
func (_m *MetricCollector) IncrementRejects() {
	_m.Called()
}

// IncrementShortCircuits provides a mock function with given fields:
func (_m *MetricCollector) IncrementShortCircuits() {
	_m.Called()
}

// IncrementSuccesses provides a mock function with given fields:
func (_m *MetricCollector) IncrementSuccesses() {
	_m.Called()
}

// IncrementTimeouts provides a mock function with given fields:
func (_m *MetricCollector) IncrementTimeouts() {
	_m.Called()
}

// Reset provides a mock function with given fields:
func (_m *MetricCollector) Reset() {
	_m.Called()
}

// UpdateRunDuration provides a mock function with given fields: runDuration
func (_m *MetricCollector) UpdateRunDuration(runDuration time.Duration) {
	_m.Called(runDuration)
}

// UpdateTotalDuration provides a mock function with given fields: timeSinceStart
func (_m *MetricCollector) UpdateTotalDuration(timeSinceStart time.Duration) {
	_m.Called(timeSinceStart)
}
