// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// DatadogClient is an autogenerated mock type for the DatadogClient type
type DatadogClient struct {
	mock.Mock
}

// Count provides a mock function with given fields: name, value, tags, rate
func (_m *DatadogClient) Count(name string, value int64, tags []string, rate float64) error {
	ret := _m.Called(name, value, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64, []string, float64) error); ok {
		r0 = rf(name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Gauge provides a mock function with given fields: name, value, tags, rate
func (_m *DatadogClient) Gauge(name string, value float64, tags []string, rate float64) error {
	ret := _m.Called(name, value, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64, []string, float64) error); ok {
		r0 = rf(name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TimeInMilliseconds provides a mock function with given fields: name, value, tags, rate
func (_m *DatadogClient) TimeInMilliseconds(name string, value float64, tags []string, rate float64) error {
	ret := _m.Called(name, value, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64, []string, float64) error); ok {
		r0 = rf(name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
